name: Serverless Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy with Serverless Framework
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Serverless Framework
        run: npm install -g serverless@3.40.0

      - name: Install project dependencies
        run: npm ci

      - name: Deploy with Serverless
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          QRCODE_BUCKET_NAME: olive-qr-codes
          QRCODE_TABLE_NAME: olive-qr-codes
          ENVIRONMENT: prod
          GA_TOURS_TABLE_NAME: ga-tours-atv
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          GOOGLE_DRIVE_TOKEN: ${{ secrets.GOOGLE_DRIVE_TOKEN }}
          GOOGLE_DRIVE_BASE_INSURANCE_FILE: '1S9zq__vv7mBDBwAua3RLIKIdE7vgjqi4vfr-b9WJ9aA'
          GOOGLE_DRIVE_PARENT_PDF_FOLDER: '135ZUg58zTdgtS32JzhDou0MDP10iiEYd'
          GOOGLE_DRIVE_PARENT_INSURANCE_FOLDER: '1vVClJS6h9WtpNXtCAqOalp_evg1YCRid'
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          OLIVE_TOOLS_SECRET: ${{ secrets.OLIVE_TOOLS_SECRET }}
